% outputs1 = stdNDM_mouse('study','DS9','bootstrapping',1,'niters',2,'verbose',0,'fmindisplay',0);
outputs2 = eNDM_mouse('study','DS9','bootstrapping',0,'niters',50,...
    'bootstrapping_endm',1,'niters_endm',10,'verbose',0,'fmindisplay',0,...
    'verbose_endm',0,'fmindisplay_endm',0);
% outputs3 = eNDM_mouse('study','DS9','bootstrapping',1,'niters',2,...
%     'bootstrapping_endm',1,'niters_endm',2,'verbose',0,'fmindisplay',0,...
%     'verbose_endm',0,'fmindisplay_endm',0,'outputs_ndm',outputs1);


% BootstrappingPlotter(outputs1);
BootstrappingPlotter(outputs2);

rng(2);
outputs3 = eNDM_mouse('study','DS6','bootstrapping',1,'niters',20,...
    'bootstrapping_endm',1,'niters_endm',20,'verbose',0,'fmindisplay',0,...
    'verbose_endm',0,'fmindisplay_endm',0,'datalist_endm',randperm(3855,2),'w_dir',1);
BootstrappingPlotter(outputs3);
CorrelationPlotter(outputs3);