% Demo and debugging script for all major NexIS functions. Make sure you
% are running this code in the top-level 'Nexis' folder of the repository!
rng(0); clear; clc;

%% 1. NexIS:global
%% 1.1.1 No bootstrapping of parameters, running and saving model
% Running NexIS
studylist = {'IbaHippInj','Hurtado'}; % Cell array of test datasets
wdir = [0,1]; % Toggle directionality fitting (s) on and off
volcorrect = 1; % ***Always keep set to 1***
usedataspace = [0,1]; % Toggle data space fitting on and off
param_init = [NaN,0,1,0.5]; % Initial fmincon parameter guesses; {gamma, alpha, beta, s}
ub = [Inf,Inf,Inf,1]; % Upper bounds for fmincon
lb = zeros(1,4); % Lower bounds for fmincon
bootstrapping_glob = 0; % Flag for bootstrapping
niters_glob = 3; % Number of bootstrapped iterations (does nothing if bootstrap flag is 0)

% Table output parameters
writetofile = 1; % Create .csv from MATLAB table
filename_out = 'NexIS_Wrapper_Global_1-1-1'; % Name of output file
filepath_out = '~/Documents/MATLAB/Nexis_Project/Results_Files_NexISWrapper'; % Save path

% Run model and create output tables for each dataset, if writetofile = 1
outputs_all = struct;
numsims = length(studylist)*length(wdir)*length(usedataspace);
for i = 1:length(studylist)
    study_i = studylist{i};
    tablename = [filename_out '_' study_i]; % Create one output table per study
    tablerowname = ['global, ' study_i ', '];
    sumtable_i = [];
    for j = 1:length(wdir)
        wdir_j = wdir(j);
        if wdir_j
            tablerowname = [tablerowname 'with dir., '];
        else
            tablerowname = [tablerowname 'no dir., '];
        end
        for k = 1:length(usedataspace)
            useds_k = usedataspace(k);
            simno = length(wdir)*length(usedataspace)*(i-1) + length(wdir)*(j-1) + k;
            fprintf('NexIS Wrapper Test %d/%d\n',simno,numsims)
            if useds_k
                tablerowname = [tablerowname 'data space'];
            else
                tablerowname = [tablerowname 'CCF space'];
            end
            outputs_ng_ijk = NexIS_global('study',study_i,...
                                          'w_dir',wdir_j,...
                                          'use_dataspace',useds_k,...
                                          'bootstrapping',bootstrapping_glob,...
                                          'niters',niters_glob,...
                                          'volcorrect',volcorrect,...
                                          'param_init',param_init,...
                                          'ub',ub,...
                                          'lb',lb);
            fieldname_ijk = [study_i '_wdir_' num2str(wdir_j) '_useds_' num2str(useds_k)];
            outputs_all.(fieldname_ijk) = outputs_ng_ijk;
            sumtable_ijk = Output2Table(outputs_ng_ijk,0,'null','null'); % create table row
            sumtable_ijk.Properties.RowNames{1} = tablerowname; % label table row
            sumtable_i = [sumtable_i; sumtable_ijk]; % add row to table
        end
    end
    if writetofile
        writetable(sumtable_i,[filepath_out filesep tablename '.csv'],'WriteRowNames',true)
    end
end

if writetofile
    save([filepath_out filesep filename_out '.mat'],'outputs_all');
end

%% 1.1.2 Relevant plotting of outputs



%     outputs_ng_ds_nobs = NexIS_global('study',studylist{i},...
%                                       'bootstrapping',0,...
%                                       'w_dir',1,...
%                                       'volcorrect',1,...
%                                       'param_init',[NaN,0,1,0.5],...
%                                       'ub',[Inf,Inf,Inf,1],...
%                                       'lb',zeros(1,4),...
%                                       'use_dataspace',1);
%     outputs_ng_ds_bs = NexIS_global('study',studylist{i},...
%                                       'bootstrapping',1,...
%                                       'niters',5,...
%                                       'w_dir',1,...
%                                       'volcorrect',1,...
%                                       'param_init',[NaN,0,1,0.5],...
%                                       'ub',[Inf,Inf,Inf,1],...
%                                       'lb',zeros(1,4),...
%                                       'use_dataspace',1);
%     outputs_ng_ds_nobs_ccf = NexIS_global('study',studylist{i},...
%                                       'bootstrapping',0,...
%                                       'w_dir',1,...
%                                       'volcorrect',1,...
%                                       'param_init',[NaN,0,1,0.5],...
%                                       'ub',[Inf,Inf,Inf,1],...
%                                       'lb',zeros(1,4),...
%                                       'use_dataspace',0);
%     outputs_ng_ds_bs_ccf = NexIS_global('study',studylist{i},...
%                                       'bootstrapping',1,...
%                                       'niters',5,...
%                                       'w_dir',1,...
%                                       'volcorrect',1,...
%                                       'param_init',[NaN,0,1,0.5],...
%                                       'ub',[Inf,Inf,Inf,1],...
%                                       'lb',zeros(1,4),...
%                                       'use_dataspace',0); % Error: Unrecognized function or variable 'pathology_fvalcalc'. line 630 in NexIS global
%     outputs_ct_ds_nobs = NexIS_SV('study',studylist{i},...
%                                   'bootstrapping',0,...
%                                   'niters',5,...
%                                   'w_dir',1,...
%                                   'volcorrect',1,...
%                                   'param_init',[NaN,0,1,0.5],...
%                                   'ub',[Inf,Inf,Inf,1],...
%                                   'lb',zeros(1,4),...
%                                   'use_dataspace',1,...
%                                   'datatype_nexis_sv','gene',...
%                                   'datalist_nexis_sv',{'Pvalb','Vip','Sst'});
% end
% C = Connectomes.default;
% C = C/max(C(:));
% seed = seed426.DS4;
% x0 = seed * 0.8;
% time_stamps = [4,8,12];
% y = eNDM_general_dir(x0,time_stamps,C,zeros(426,1),0.2,3.5,0.65,0,0,0,'analytic',0);
% corr(y(:), data426.DS4(:),'rows','complete')^2