function BrainframePlot()
%% 2.2 Figure 1, brainframes
matdir1 = '/Users/justintorok/Documents/MATLAB/Brainframe-Dev/Brainframe';
figdir = '/Users/justintorok/Documents/MATLAB/MISS/Figures';
addpath('/Users/justintorok/Documents/MATLAB/Brainframe-Dev/Brainframe')
load([matdir filesep 'default_mouse.mat'],'input_struct');

reggroups = zeros(213,1); %Chunk of code to define region_groups
amy = 1:11; cer = 12:23; sub = 24:26; hip = 27:37; hyp = 38:57; 
ncx = 58:95; med = 96:120; mid = 121:141; olf = 142:149; pal = 150:157;
pon = 158:170; str = 171:178; tha = 179:213;
reggroups(amy) = 1; reggroups(cer) = 2; reggroups(sub) = 3; 
reggroups(hip) = 4; reggroups(hyp) = 5; reggroups(ncx) = 6;
reggroups(med) = 7; reggroups(mid) = 8; reggroups(olf) = 9;
reggroups(pal) = 10; reggroups(pon) = 11; reggroups(str) = 12;
reggroups(tha) = 13;
reggroups = [reggroups;reggroups];
cmap = lines(length(unique(reggroups))); %Creating colormap

%% 2.2.1 IbaHippInj end pathology
datinput = ibahippinj_end;
datinput(isnan(datinput)) = 0;
imglabel = 'IbaHippInj_End';
imgview = [0 0 1];
input_struct_ibahipp = brainframe_inputs_mouse(matdir1,'region_groups',reggroups,...
                                             'cmap',cmap,...
                                             'xfac',10,...
                                             'pointsize',1,...
                                             'voxUreg',1,...
                                             'data',datinput,...
                                             'norm_method','mean',...
                                             'center',[1 2],...
                                             'bgcolor','w',...
                                             'con_rescale',20,...
                                             'img_labels',imglabel,...
                                             'img_format','tiffn',...
                                             'img_views',imgview,...
                                             'img_directory',figdir,...
                                             'savenclose',0);
brainframe(input_struct_ibahipp);

%% 2.2.2 Hurtado end pathology
% datinput = taudata_all.Hurtado(:,end);
datinput(isnan(datinput)) = 0;
imglabel = 'Hurtado_End';
imgview = [0 0 -1];
input_struct_hurtado = brainframe_inputs_mouse(matdir1,'region_groups',reggroups,...
                                             'cmap',cmap,...
                                             'xfac',6,...
                                             'pointsize',15,...
                                             'voxUreg',1,...
                                             'data',datinput,...
                                             'norm_method','mean',...
                                             'center',[1 1.5],...
                                             'sphere',0,...
                                             'sphere_npts',15,...
                                             'bgcolor','w',...
                                             'img_labels',imglabel,...
                                             'img_format','tiffn',...
                                             'img_views',imgview,...
                                             'img_directory',figdir,...
                                             'savenclose',0);
brainframe(input_struct_hurtado);
view([0 0 1])
end