function BrainframeModelPredPlot(outstruct,datset,matdir_,savenclose_,figdir_)

brainframedir = '/Users/justintorok/Documents/MATLAB/Brainframe-Dev/Brainframe';
addpath(brainframedir)

reggroups_ = zeros(213,1); %Chunk of code to define region_groups
amy = 1:11; cer = 12:23; sub = 24:26; hip = 27:37; hyp = 38:57;
ncx = 58:95; med = 96:120; mid = 121:141; olf = 142:149; pal = 150:157;
pon = 158:170; str = 171:178; tha = 179:213;
reggroups_(amy) = 1; reggroups_(cer) = 2; reggroups_(sub) = 3; 
reggroups_(hip) = 4; reggroups_(hyp) = 5; reggroups_(ncx) = 6;
reggroups_(med) = 7; reggroups_(mid) = 8; reggroups_(olf) = 9;
reggroups_(pal) = 10; reggroups_(pon) = 11; reggroups_(str) = 12;
reggroups_(tha) = 13;
reggroups_ = [reggroups_;reggroups_];
cmap_ = hsv(length(unique(reggroups_)));
modelnames = fieldnames(outstruct.(datset));

if ~isnan(outstruct.(datset).(modelnames{1}).nexis_global.Full.init.seed)
    datinput = outstruct.(datset).(modelnames{1}).nexis_global.Full.init.seed;
else
    datinput = logical(outstruct.(datset).(modelnames{1}).nexis_global.Full.init.baseline);
end
datinput_data = DataToCCF(datinput,datset,matdir_);
nany = isnan(datinput_data);
datinput_data(nany) = 0;
imglab = sprintf('SeedBrainframe_Data_%s',datset);
input_struct_data = brainframe_inputs_mouse(brainframedir,...
                                             'region_groups',reggroups_,...
                                             'cmap',cmap_,...
                                             'xfac',4,...
                                             'sphere',1,...
                                             'sphere_npts',50,...
                                             'pointsize',5,...
                                             'voxUreg',1,...
                                             'data',datinput_data,...
                                             'norm_method','max',...
                                             'bgcolor','w',...
                                             'img_labels',imglab,...
                                             'img_format','tiffn',...
                                             'img_directory',figdir_,...
                                             'savenclose',savenclose_);
brainframe(input_struct_data);

ngrad = 3;
for m = 1:length(modelnames)
    datinput = outstruct.(datset).(modelnames{m}).nexis_global.Full.predicted;
    datinput_data = DataToCCF(datinput,datset,matdir_);
    tpts = outstruct.(datset).(modelnames{m}).nexis_global.Full.time_stamps;
    for k = 1:size(datinput_data,2)
        datinput_k = datinput_data(:,k);
        nany = isnan(datinput_k);
        datinput_k(nany) = 0;
        xfac = 0.15*(max(datinput_k)/max(datinput_data(~nany,1)))^(1/3);
        reggroups_data = zeros(length(reggroups_),1);
        cmap_data = zeros(length(unique(reggroups_))*ngrad,3);
        for i = 1:length(unique(reggroups_))
            cmap_i = cmap_(i,:);
            reggroup_i_inds = (reggroups_ == i);
            for j = 1:ngrad
                newgroupind = (i-1)*ngrad + j;
                thresh_j = j*100/ngrad;
                zeroinds = (reggroups_data == 0);
                threshinds = (datinput_k <= prctile(nonzeros(datinput_k),thresh_j));
                ij_inds = (zeroinds + threshinds + reggroup_i_inds == 3);
                reggroups_data(ij_inds) = newgroupind;
                cmap_data(newgroupind,:) = (1/2)*cmap_i + (1/2)*(((ngrad-j)*ones(1,3) + j*cmap_i)/ngrad);
            end
        end
        imglab = sprintf('ModelPredBrainframe_Data_%s_Model_%s_t%d',datset,modelnames{m},tpts(k));
        input_struct_data = brainframe_inputs_mouse(brainframedir,'data',datinput_k,...
                                                    'voxUreg',1,...
                                                    'xfac',xfac,...
                                                    'pointsize',5,...
                                                    'norm_method','max',...
                                                    'bgcolor','w',...
                                                    'img_format','tiffn',...
                                                    'cmap',cmap_data,...
                                                    'region_groups',reggroups_data,...
                                                    'centered',[0 1],...
                                                    'img_directory',figdir_,...
                                                    'img_labels',imglab,...
                                                    'img_renderer','painters',...
                                                    'savenclose',savenclose_);
        brainframe(input_struct_data);
    end
end
end